services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env.db
    volumes:
      - my-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  
  backend:
    image: paularinze/book-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - database
    networks:
      - backend
      - frontend
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: paularinze/book-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

volumes:
  my-db:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge