apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-backend
spec:
  selector:
    matchLabels:
      app: book-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: book-backend
    spec:
      containers:
      - name: book-backend
        image: paularinze/book-backend:latest
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: book-backend-service
spec:
  selector:
    app: book-backend

  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80