apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-frontend
spec:
  selector:
    matchLabels:
      app: book-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: book-frontend
    spec:
      containers:
      - name: book-frontend
        image: paularinze/book-backend:latest
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: book-frontend-service
spec:
  selector:
    app: book-frontend

  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80