name: Push Frontend image to Image registry

on:
  push:
    branches: ["master"]
    paths:
      - 'frontend/**'

env: 
  REGISTRY: docker.io
  IMG_NAME: ${{secrets.BACKEND_IMG}}

jobs:
  push_to_registry:
    name: Build and Push Image to Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.FRONTEND_IMG}}

      - name: Build & push the image
        id: pushbuild
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: push_to_registry
    uses: ./.github/workflows/cd-frontend.yaml
    secrets: inherit